
nginx:
    image: nginx:latest
    command: "nginx -g 'daemon off;'"
    container_name: nginx
    links:
        - php
    ports:
        - "8080:80"
    volumes:
        - ./www/:/var/www
        - ./docker/builder/nginx/conf.d:/etc/nginx/conf.d
        - ./docker/builder/nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /var/www
php:
    build: ./docker/builder/php/
    command: "/data/php-fpm.sh"
    container_name: php-5.6
    links:
        - db  
    ports:
        - "9000:9000"
    volumes:
        - ./www:/var/www
        - ./docker/builder/php:/data
    working_dir: /var/www
db:
    image: mysql:latest
    container_name: mysql-5.7
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: dev
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: myapp 
node:
    build: ./docker/builder/node/
