version: '2'
services:
    php-5.6-apache:
        build: ./docker/builder/php56apache
        container_name: php-5.6-apache
        ports:
            - "9001:9000"
            - "8081:80"
        working_dir: /var/www/html
        volumes:
            - ./www:/var/www/html
            - ./docker/builder/php56apache/apache2/apache2.conf:/etc/apache2/apache2.conf
            - ./docker/builder/php56apache/apache2/sites-enabled:/etc/apache2/sites-enabled                 
    php-5.6-fpm:
        build: ./docker/builder/php56fpm
        container_name: php-5.6-fpm
        command: "/data/php-fpm-user.sh"
        ports:
            - "9002:9000"
        volumes:
            - ./www:/var/www
            - ./docker/builder/php56fpm/php-fpm-user.sh:/data/php-fpm-user.sh
        working_dir: /var/www
    db:
        image: mysql:latest
        container_name: mysql-5.7
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: dev
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: myapp
    nginx:
        image: nginx
        command: "nginx -g 'daemon off;'"
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./www/:/var/www
            - ./docker/builder/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/builder/nginx/nginx.conf:/etc/nginx/nginx.conf
        working_dir: /var/www
        links:
            - "php-5.6-fpm:php"