version: '2'
services:
    nginx:
        image: nginx:latest
        command: "nginx -g 'daemon off;'"
        container_name: nginx
        volumes:
            - ./www/:/var/www
            - ./docker/builder/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/builder/nginx/nginx.conf:/etc/nginx/nginx.conf
        working_dir: /var/www